<a href="https://colab.research.google.com/github/iamridam/Data-Science/blob/master/Numpy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Comparing Speed of list with numpy array

In [ ]:
N = 100

In [ ]:
%%time
list_ = list(range(N))
for i in range(N):
  list_[i] = list_[i] * list_[i]

CPU times: user 39 µs, sys: 0 ns, total: 39 µs
Wall time: 43.9 µs


In [ ]:
%%time 
import numpy as np
arr = np.arange(N)
arr = arr * arr

CPU times: user 743 µs, sys: 0 ns, total: 743 µs
Wall time: 7.13 ms


In [ ]:
arr = np.array([1, 2.9, 3])
type(arr)

numpy.ndarray

In [ ]:
arr.dtype

dtype('float64')

In [ ]:
arr1 = np.random.randn(2,3)

In [ ]:
arr1

array([[ 0.0981021 ,  0.67514388,  0.69148168],
       [-0.4249127 , -1.68265116,  0.56636373]])

This is very interesting example where it shows how indexing is done for 3-D array

In [ ]:
arr = np.random.randint(1, 10, (4,2,2))

In [ ]:
arr

array([[[7, 6],
        [3, 3]],

       [[5, 5],
        [6, 1]],

       [[2, 1],
        [3, 6]],

       [[8, 2],
        [4, 7]]])

In [ ]:
my_indices = [0, 2, 3]

In [ ]:
arr[my_indices]

array([[[7, 6],
        [3, 3]],

       [[2, 1],
        [3, 6]],

       [[8, 2],
        [4, 7]]])

Question Related to Numpy Padhai

In [ ]:
import numpy as np
arr2 = np.arange(6).reshape(3,2)
arr2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
arr2[:, 0]

array([0, 2, 4])

In [ ]:
import numpy as np
a = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10]])
print(a[ : : -1])

[[ 6  7  8  9 10]
 [ 1  2  3  4  5]]


Collect numbers for masses and diameters of plannet and store it as series object. Compute the density of these plannets. 

In [16]:
import pandas as pd
import numpy as np

plannet_mass = pd.Series([20,30,40])
plannet_diameter = pd.Series([2,3,4])

In [17]:
volume = []

for diameter in plannet_diameter:
  vol = (4/3)*3.14*pow(diameter,3)
  volume.append(vol)

plannet_volume = pd.Series(volume)  

In [18]:
plannet_density = plannet_mass/plannet_volume

In [19]:
plannet_density

0    0.597134
1    0.265393
2    0.149283
dtype: float64

Given the density series replace all values which has NAN with the mean density of all plannets.

In [20]:
mean_density = np.mean(plannet_density)

In [23]:
NaN = np.nan
plannet_density[4] = NaN

In [25]:
plannet_density[pd.isnull(plannet_density)] = mean_density

In [26]:
plannet_density

0    0.597134
1    0.265393
2    0.149283
4    0.337270
dtype: float64

**Nifty Case Study**

In [53]:
import pandas as pd

In [2]:
from google.colab import files
uploaded = files.upload()

Saving nifty-200623-235920.csv to nifty-200623-235920.csv


In [63]:
nifty = pd.read_csv('nifty-200623-235920.csv', index_col = 0).iloc[ : , 0]

In [55]:
nifty.head()

Date
01-Jan-2019    10910.10
02-Jan-2019    10792.50
03-Jan-2019    10672.25
04-Jan-2019    10727.35
07-Jan-2019    10771.80
Name: Close, dtype: float64

Percentage of days market close higher than the previous day

In [56]:
difference = (nifty.values[1 : ] - nifty.values[ : -1])
k = 0
for i in difference:
  if (i>0):
    k = k+1
percent_days = k/(len(nifty))
print(percent_days)

0.5265306122448979


In [57]:
 import numpy as np
 percent_days = np.sum((nifty.values[1 : ] - nifty.values[ : -1])>0)/len(nifty)
 print(percent_days)

0.5265306122448979


In [64]:
new_index = map(pd.Timestamp, nifty.index)
new_nifty = pd.Series(nifty, index = new_index)
new_nifty

2019-01-01    10910.10
2019-01-02    10792.50
2019-01-03    10672.25
2019-01-04    10727.35
2019-01-07    10771.80
                ...   
2019-12-24    12214.55
2019-12-26    12126.55
2019-12-27    12245.80
2019-12-30    12255.85
2019-12-31    12168.45
Name: Close, Length: 245, dtype: float64

In [65]:
new_nifty.rolling('5d').mean()

2019-01-01    10910.100000
2019-01-02    10851.300000
2019-01-03    10791.616667
2019-01-04    10775.550000
2019-01-07    10723.800000
                  ...     
2019-12-24    12249.700000
2019-12-26    12201.283333
2019-12-27    12212.412500
2019-12-30    12209.400000
2019-12-31    12223.366667
Name: Close, Length: 245, dtype: float64

In [69]:
import pandas as pd 
data = [0, 1, 1, 2, 3, 5, 8, 13, 21]
s = pd.Series(data)
b = s.diff()
print(b.iloc[5])


2.0


In [71]:
b

0    NaN
1    1.0
2    0.0
3    1.0
4    1.0
5    2.0
6    3.0
7    5.0
8    8.0
dtype: float64

In [74]:
data = [1,2,3,4]
s = pd.Series(data, index = [1,2,3,4])
b = (s>2).any()

In [75]:
b

True