<a href="https://colab.research.google.com/github/iamridam/Data-Science/blob/master/Numpy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Comparing Speed of list with numpy array

In [ ]:
N = 100

In [ ]:
%%time
list_ = list(range(N))
for i in range(N):
  list_[i] = list_[i] * list_[i]

CPU times: user 39 µs, sys: 0 ns, total: 39 µs
Wall time: 43.9 µs


In [ ]:
%%time 
import numpy as np
arr = np.arange(N)
arr = arr * arr

CPU times: user 743 µs, sys: 0 ns, total: 743 µs
Wall time: 7.13 ms


In [ ]:
arr = np.array([1, 2.9, 3])
type(arr)

numpy.ndarray

In [ ]:
arr.dtype

dtype('float64')

In [ ]:
arr1 = np.random.randn(2,3)

In [ ]:
arr1

array([[ 0.0981021 ,  0.67514388,  0.69148168],
       [-0.4249127 , -1.68265116,  0.56636373]])

This is very interesting example where it shows how indexing is done for 3-D array

In [ ]:
arr = np.random.randint(1, 10, (4,2,2))

In [ ]:
arr

array([[[7, 6],
        [3, 3]],

       [[5, 5],
        [6, 1]],

       [[2, 1],
        [3, 6]],

       [[8, 2],
        [4, 7]]])

In [ ]:
my_indices = [0, 2, 3]

In [ ]:
arr[my_indices]

array([[[7, 6],
        [3, 3]],

       [[2, 1],
        [3, 6]],

       [[8, 2],
        [4, 7]]])

Question Related to Numpy Padhai

In [ ]:
import numpy as np
arr2 = np.arange(6).reshape(3,2)
arr2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
arr2[:, 0]

array([0, 2, 4])

In [ ]:
import numpy as np
a = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10]])
print(a[ : : -1])

[[ 6  7  8  9 10]
 [ 1  2  3  4  5]]


Collect numbers for masses and diameters of plannet and store it as series object. Compute the density of these plannets. 

In [ ]:
import pandas as pd
import numpy as np

plannet_mass = pd.Series([20,30,40])
plannet_diameter = pd.Series([2,3,4])

In [ ]:
volume = []

for diameter in plannet_diameter:
  vol = (4/3)*3.14*pow(diameter,3)
  volume.append(vol)

plannet_volume = pd.Series(volume)  

In [ ]:
plannet_density = plannet_mass/plannet_volume

In [ ]:
plannet_density

0    0.597134
1    0.265393
2    0.149283
dtype: float64

Given the density series replace all values which has NAN with the mean density of all plannets.

In [ ]:
mean_density = np.mean(plannet_density)

In [ ]:
NaN = np.nan
plannet_density[4] = NaN

In [ ]:
plannet_density[pd.isnull(plannet_density)] = mean_density

In [ ]:
plannet_density

0    0.597134
1    0.265393
2    0.149283
4    0.337270
dtype: float64

**Nifty Case Study**

In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving nifty-200623-235920.csv to nifty-200623-235920.csv


In [ ]:
nifty = pd.read_csv('nifty-200623-235920.csv', index_col = 0).iloc[ : , 0]

In [ ]:
nifty.head()

Date
01-Jan-2019    10910.10
02-Jan-2019    10792.50
03-Jan-2019    10672.25
04-Jan-2019    10727.35
07-Jan-2019    10771.80
Name: Close, dtype: float64

Percentage of days market close higher than the previous day

In [ ]:
difference = (nifty.values[1 : ] - nifty.values[ : -1])
k = 0
for i in difference:
  if (i>0):
    k = k+1
percent_days = k/(len(nifty))
print(percent_days)

0.5265306122448979


In [ ]:
 import numpy as np
 percent_days = np.sum((nifty.values[1 : ] - nifty.values[ : -1])>0)/len(nifty)
 print(percent_days)

0.5265306122448979


In [ ]:
new_index = map(pd.Timestamp, nifty.index)
new_nifty = pd.Series(nifty, index = new_index)
new_nifty

2019-01-01    10910.10
2019-01-02    10792.50
2019-01-03    10672.25
2019-01-04    10727.35
2019-01-07    10771.80
                ...   
2019-12-24    12214.55
2019-12-26    12126.55
2019-12-27    12245.80
2019-12-30    12255.85
2019-12-31    12168.45
Name: Close, Length: 245, dtype: float64

In [ ]:
new_nifty.rolling('5d').mean()

2019-01-01    10910.100000
2019-01-02    10851.300000
2019-01-03    10791.616667
2019-01-04    10775.550000
2019-01-07    10723.800000
                  ...     
2019-12-24    12249.700000
2019-12-26    12201.283333
2019-12-27    12212.412500
2019-12-30    12209.400000
2019-12-31    12223.366667
Name: Close, Length: 245, dtype: float64

In [ ]:
import pandas as pd 
data = [0, 1, 1, 2, 3, 5, 8, 13, 21]
s = pd.Series(data)
b = s.diff()
print(b.iloc[5])


2.0


In [ ]:
b

0    NaN
1    1.0
2    0.0
3    1.0
4    1.0
5    2.0
6    3.0
7    5.0
8    8.0
dtype: float64

In [ ]:
data = [1,2,3,4]
s = pd.Series(data, index = [1,2,3,4])
b = (s>2).any()
print(b)

Creating a user defined DataFrame

In [14]:
import numpy as np
import pandas as pd
def create_dataframe(nrows, ncols):
  arr = np.random.randint(1, 20, [nrows,ncols])
  df = pd.DataFrame(arr)
  df.index = ['R' + str(x) for x in np.arange(1,nrows+1)]
  df.columns = ['C' + str(x) for x in np.arange(1,ncols+1)]
  return df

In [18]:
df = create_dataframe(3,4)

In [19]:
df

C1  C2  C3  C4
R1  19  19  12  16
R2   6   9  13  17
R3  15  18  18   5

In [20]:
df.shape

(3, 4)

In [25]:
def row_mean(df):
    df.loc['mean_col'] = [np.mean(df[col]) for col in df.columns]
    df.loc['Mean_col'] = df.mean() # much more faster
    return df


In [26]:
row_mean(df)

C1         C2         C3         C4
R1        19.000000  19.000000  12.000000  16.000000
R2         6.000000   9.000000  13.000000  17.000000
R3        15.000000  18.000000  18.000000   5.000000
mean_col  13.333333  15.333333  14.333333  12.666667
Mean_col  13.333333  15.333333  14.333333  12.666667

In [12]:
import seaborn as sns
import numpy as np
import pandas as pd

df = sns.load_dataset('planets')

In [7]:
df.shape

(1035, 6)

In [10]:
for row in df.index:
  for col in df.columns:
    if pd.isnull(df.loc[row,col]):
      df.drop(row, inplace = True)
      break

In [11]:
df.shape

(498, 6)

In [13]:
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [23]:
per_75 = df.distance.quantile(0.75)
df[(df['year'] >= 2010) & 
    ((df['method']=='Radial Velocity') | (df['method']=='Transit')) &
    (df['distance'] > per_75)]

method  number  orbital_period  mass  distance  year
99    Transit       1        6.212290   NaN     380.0  2010
101   Transit       1       13.240600   NaN     345.0  2010
102   Transit       1        2.994330   NaN     560.0  2010
103   Transit       1        2.828042   NaN    1150.0  2010
104   Transit       1        4.035190   NaN    1060.0  2010
...       ...     ...             ...   ...       ...   ...
1021  Transit       1        2.484193   NaN     260.0  2013
1023  Transit       1        2.175176   NaN     550.0  2012
1024  Transit       1        3.662387   NaN     240.0  2012
1026  Transit       1        0.925542   NaN     470.0  2014
1028  Transit       1        3.352057   NaN    3200.0  2012

[154 rows x 6 columns]

Modify method column to have only abbreviation of each method.

In [24]:
import seaborn as sns
import numpy as np
import pandas as pd

df = sns.load_dataset('planets')

In [25]:
short_names = {}
for i in df.method.unique():
  short_names[i] = ''.join([x[0] for x in i.split(' ')])

In [26]:
short_names

{'Astrometry': 'A',
 'Eclipse Timing Variations': 'ETV',
 'Imaging': 'I',
 'Microlensing': 'M',
 'Orbital Brightness Modulation': 'OBM',
 'Pulsar Timing': 'PT',
 'Pulsation Timing Variations': 'PTV',
 'Radial Velocity': 'RV',
 'Transit': 'T',
 'Transit Timing Variations': 'TTV'}

In [27]:
def short_method(s):
  return short_names.get(s,s)

In [29]:
df['short_method'] = df['method'].apply(short_method)

In [30]:
df

method  number  orbital_period  ...  distance  year  short_method
0     Radial Velocity       1      269.300000  ...     77.40  2006            RV
1     Radial Velocity       1      874.774000  ...     56.95  2008            RV
2     Radial Velocity       1      763.000000  ...     19.84  2011            RV
3     Radial Velocity       1      326.030000  ...    110.62  2007            RV
4     Radial Velocity       1      516.220000  ...    119.47  2009            RV
...               ...     ...             ...  ...       ...   ...           ...
1030          Transit       1        3.941507  ...    172.00  2006             T
1031          Transit       1        2.615864  ...    148.00  2007             T
1032          Transit       1        3.191524  ...    174.00  2007             T
1033          Transit       1        4.125083  ...    293.00  2008             T
1034          Transit       1        4.187757  ...    260.00  2008             T

[1035 rows x 7 columns]

In [47]:
import seaborn as sns
import numpy as np
import pandas as pd

df = sns.load_dataset('planets')

In [48]:
df = df[df['year'] >= 2010]
df = df.groupby('method')['method'].count()

In [49]:
df

method
Astrometry                         2
Eclipse Timing Variations          6
Imaging                           18
Microlensing                      13
Orbital Brightness Modulation      3
Pulsar Timing                      1
Radial Velocity                  215
Transit                          335
Transit Timing Variations          4
Name: method, dtype: int64

In [44]:
df1 = sns.load_dataset('planets')
df1 = df1.groupby('method')['method'].count()


In [52]:
fraction = df/df1
fraction 

method
Astrometry                       1.000000
Eclipse Timing Variations        0.666667
Imaging                          0.473684
Microlensing                     0.565217
Orbital Brightness Modulation    1.000000
Pulsar Timing                    0.200000
Pulsation Timing Variations           NaN
Radial Velocity                  0.388788
Transit                          0.843829
Transit Timing Variations        1.000000
Name: method, dtype: float64