<a href="https://colab.research.google.com/github/iamridam/Data-Science/blob/master/Numpy_case_study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Case Study

In [ ]:
cric_data = np.loadtxt('cric_data-200320-181217.tsv',
                       skiprows=1)

In [ ]:
cric_data.shape

(225, 4)

In [ ]:
cric_data = cric_data[ :, [1,2,3]]
print(cric_data.shape)

(225, 3)


In [ ]:
sachin = cric_data[ :, 0]
rahul = cric_data[ :, 1]
india = cric_data[ :, 2]

In [ ]:
def stats(col):
  print('Mean', np.mean(col))
  print('Mean', np.median(col))
  print('IQR', ((np.percentile(col,75) - np.percentile(col,25))))

In [ ]:
stats(sachin)

Mean 39.87555555555556
Mean 27.0
IQR 57.0


In [ ]:
# Hiistogram of 10 bins
np.histogram(sachin)

(array([99, 36, 28, 16, 11, 17,  8,  8,  1,  1]),
 array([  0. ,  18.6,  37.2,  55.8,  74.4,  93. , 111.6, 130.2, 148.8,
        167.4, 186. ]))

In [ ]:
#Finding mean of Sachin's score groupby 25 matches
# axis 1 gives sum along the rows
sachin_25 = sachin.reshape(9,25)
np.mean(sachin_25, axis = 1)

array([33.96, 49.4 , 38.48, 40.16, 39.36, 38.2 , 44.6 , 39.52, 35.2 ])

In [ ]:
# sachin average for score greater than 100
np.mean(sachin[sachin >= 100])

125.0

In [ ]:
qrs = np.percentile(india, [25,50,75, 100])
print(qrs)
print(qrs.shape)

[175. 216. 273. 499.]
(4,)


In [ ]:
qrs = qrs.reshape(4,1)

In [ ]:
qrs.shape

(4, 1)

In [ ]:
indices = qrs > india

In [ ]:
indices.shape

(4, 225)

In [ ]:
sachin[indices[0,:]]

array([18., 14.,  0., 62., 46., 65.,  0., 39., 48.,  3., 11., 65., 27.,
       28.,  3.,  4., 15., 40.,  5.,  8., 89.,  0.,  0.,  1.,  0.,  0.,
       81., 13.,  2., 36., 12., 19.,  0.,  6., 35.,  0., 44.,  3., 47.,
       17., 35., 33.,  7.,  9.,  2., 11., 17.,  1., 10.,  0., 23.,  1.,
        2., 25.,  0.])

In [ ]:
sachin[indices[0]]

array([18., 14.,  0., 62., 46., 65.,  0., 39., 48.,  3., 11., 65., 27.,
       28.,  3.,  4., 15., 40.,  5.,  8., 89.,  0.,  0.,  1.,  0.,  0.,
       81., 13.,  2., 36., 12., 19.,  0.,  6., 35.,  0., 44.,  3., 47.,
       17., 35., 33.,  7.,  9.,  2., 11., 17.,  1., 10.,  0., 23.,  1.,
        2., 25.,  0.])

In [ ]:
for i in range(4):
  print('Sachin mean in %d quartile is %f' % (i, np.mean(sachin[indices[i]])))

Sachin mean in 0 quartile is 19.672727
Sachin mean in 1 quartile is 28.180180
Sachin mean in 2 quartile is 31.688623
Sachin mean in 3 quartile is 39.799107


In [ ]:
sac_vs_rahul = cric_data[:, 0:2]
snr = np.argmax(sac_vs_rahul, axis=1)

In [ ]:
np.where(snr == 0, 'Sachin','Rahul')

array(['Sachin', 'Rahul', 'Rahul', 'Sachin', 'Sachin', 'Rahul', 'Rahul',
       'Sachin', 'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Sachin',
       'Sachin', 'Rahul', 'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Sachin',
       'Rahul', 'Sachin', 'Sachin', 'Rahul', 'Sachin', 'Sachin', 'Sachin',
       'Sachin', 'Sachin', 'Sachin', 'Sachin', 'Rahul', 'Rahul', 'Sachin',
       'Rahul', 'Rahul', 'Sachin', 'Rahul', 'Sachin', 'Sachin', 'Sachin',
       'Sachin', 'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Sachin', 'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Sachin', 'Sachin', 'Sachin', 'Sachin', 'Rahul', 'Sachin', 'Rahul',
       'Rahul', 'Sachin', 'Sachin', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Rahul', 'Rahul',
       'Rahul', 'Sachin', 'Sachin', 'Sachin', 'Rahul', 'Sachin', 'Sachin',
       'Sachin', 'Sachin', 'Sachin', 'Sachin'

In [ ]:
x_arr = np.arange(0, 101, 5)
x_arr.shape

(21,)

In [ ]:
x_arr = x_arr.reshape(x_arr.shape[0],1)
x_arr.shape

(21, 1)

In [ ]:
idi = sachin >= x_arr
idi.shape

(21, 225)

In [ ]:
for i in range(idi.shape[0]):
  print(x_arr[i, 0], np.mean(sachin[idi[i]])-x_arr[i, 0] )

0 39.87555555555556
5 45.61363636363637
10 47.48026315789474
15 47.45255474452555
20 46.824
25 44.10084033613445
30 45.13461538461539
35 43.24742268041237
40 44.05882352941177
45 43.41558441558442
50 43.98529411764706
55 42.317460317460316
60 38.67213114754098
65 37.654545454545456
70 37.08163265306122
75 34.347826086956516
80 30.75
85 28.650000000000006
90 27.400000000000006
95 26.433333333333337
100 25.0


In [ ]:
sachin_cum_score = np.cumsum(sachin)

In [ ]:
sachin_cum_score

array([ 100.,  111.,  119.,  190.,  294.,  312.,  320.,  406.,  418.,
        503.,  521.,  525.,  532.,  569.,  583.,  583.,  587.,  587.,
        608.,  609.,  671.,  671.,  809.,  847.,  849.,  895.,  960.,
        960.,  999., 1047., 1188., 1250., 1262., 1263., 1304., 1315.,
       1318., 1504., 1515., 1542., 1569., 1620., 1638., 1670., 1816.,
       1821., 1866., 2007., 2019., 2084., 2111., 2118., 2134., 2136.,
       2164., 2170., 2293., 2413., 2420., 2423., 2423., 2504., 2506.,
       2560., 2682., 2686., 2700., 2700., 2800., 2815., 2815., 2872.,
       2971., 3008., 3046., 3078., 3099., 3131., 3171., 3171., 3176.,
       3184., 3189., 3189., 3239., 3269., 3306., 3395., 3399., 3497.,
       3580., 3673., 3673., 3725., 3877., 3878., 3886., 3979., 4024.,
       4050., 4050., 4051., 4051., 4067., 4114., 4203., 4206., 4207.,
       4260., 4276., 4276., 4357., 4371., 4449., 4455., 4560., 4682.,
       4691., 4699., 4727., 4762., 4831., 4844., 4941., 5034., 5036.,
       5072., 5111.,

In [ ]:
np.histogram(sachin_cum_score, bins=10, range=(0, 10000))

(array([29, 18, 26, 25, 26, 26, 23, 22, 30,  0]),
 array([    0.,  1000.,  2000.,  3000.,  4000.,  5000.,  6000.,  7000.,
         8000.,  9000., 10000.]))